name: Generate Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  Generating_Metrics:
    runs-on: ubuntu-latest
    steps:
      # cartoon screenshot
      - name: cartoon
        uses: lowlighter/metrics@latest
        with:
          filename: Images/Dynamic/cartoon.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_screenshot: yes
          plugin_screenshot_title: Cartoon of the day
          plugin_screenshot_url: https://comic.browserling.com/random
          plugin_screenshot_selector: "#cartoon img"
          plugin_screenshot_background: no
          config_padding: 0, 8 + 1%
      # joke screenshot
      - name: joke
        uses: lowlighter/metrics@latest
        with:
          filename: Images/Dynamic/joke.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_screenshot: yes
          plugin_screenshot_title: Joke of the day
          plugin_screenshot_url: https://readme-jokes.vercel.app/api?bgColor=%23fff&hideBorder&textColor=%23000&qColor=%23000&aColor=%2325b
          plugin_screenshot_selector: ".container"
          plugin_screenshot_background: no
          config_padding: 0, 8 + 5%
      # meme screenshot
      - name: meme
        uses: lowlighter/metrics@latest
        with:
          filename: Images/Dynamic/meme.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_screenshot: yes
          plugin_screenshot_title: Meme of the day
          plugin_screenshot_url: https://programmerhumor.io/?bimber_random_post=true
          plugin_screenshot_selector: ".g1-frame-inner"
          plugin_screenshot_background: no
          config_padding: 0, 8 + 1%
